language: c
dist: xenial
sudo: required
before_install:
  - sudo apt-get install python python-numpy python-pip
  - sudo apt-get install gfortran
  - sudo apt-get install libnetcdf-dev libnetcdff-dev
  - sudo apt-get install --reinstall openmpi-bin libopenmpi-dev
script: pip install numpy
